enum BillType {
    "normal", 
    "icash", 
    "network", 
    "oil"
};

interface Bill {
    void Bill(long p_year, long p_month, long p_day, long p_amount, BillType p_type, [Const] DOMString p_comment);
    long getAmount();
    BillType getType();
    void info();
};

interface CredictCardBase {
    void CredictCardBase([Const] DOMString p_name, optional long p_dueDate = 1);
    long getDisCount();
    void addPreAssignBill(Bill b);
    void addAssignBill(Bill b);
    void clearAssignBill();
    long getDisCountForCommit(); 
    void commitCurrentAssign();
    void dumpBestAssign();
    //void _getMergeList([Ref] vector<Bill> mergeList);
};

interface CredictCardHN {
    void CredictCardHN([Const] DOMString p_name);
    long getDisCount();
};
CredictCardHN implements CredictCardBase;

interface CredictCardYS {
    void CredictCardYS([Const] DOMString p_name);
    long getDisCount();
};
CredictCardYS implements CredictCardBase;

interface CredictCardHNICash {
    void CredictCardHNICash([Const] DOMString p_name);
    long getDisCount();
};
CredictCardHNICash implements CredictCardBase;

interface CredictCardMgr {
    void CredictCardMgr();
    void addBill(Bill b, CredictCardBase card);
    void addCard(CredictCardBase card);
    void assignCard();
};

